version: "2.1"

services:

  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=America/Colombia
      - TOKEN=daa034b7-046f-4008-b840-0b9833182928
      - LOG_FILE=flase
    restart: unless-stopped
