version: "3.8"
services:

#------------------------PORTAINER-------------------------------------
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart:  always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/chris/Documentos/Docker/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    ports:
      - 9000:9000
#----------------------------NODE-RED----------------------------------
  nodered:
    container_name: Node-red
    image: nodered/node-red:latest
    restart: always
    ports:
      - "1880:1880" 
    volumes:
      - /home/chris/Documentos/Docker/nodered:/data
#----------------------------MOSQUITTO--------------------------------
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001" 
    volumes:
      - /home/chris/Documentos/Docker/mosquitto/config:/mqtt/config
      - /home/chris/Documentos/Docker/mosquitto/data:/mqtt/data
      - /home/chris/Documentos/Docker/mosquitto/log:/mqtt/log
volumes:
  config:
  data:
  log:
