version: "2.1"
services:

#---------------------------SAMBA---------------------------------
  samba:
    image: dperson/samba:rpi
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:130
      - 445:445
    volumes:
      - /home/pi/media:/media
      
#--------------------------WIREGUARD-----------------------------
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mendoza
      - SERVERURL=1.1.1.1 #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /root/wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
#--------------------------PiHole---------------------------------
pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" 
      - "80:80/tcp"
    environment:
      TZ: 'America/Colombia/Medellin'
      WEBPASSWORD: 'raspilarios'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    
    cap_add:
      - NET_ADMIN       
    restart: unless-stopped
#------------------------RTORRENT (CORTESÍA DEL PELADO)-----------
  rtorrent:
    image: pablokbs/rutorrent-armhf
    ports:
      - 80:80
      - 51413:51413
      - 6881:6881/udp
    volumes:
      - /home/pi/torrents-config/rtorrents:/config/rtorrent
      - /home/pi/downloads:/downloads
    restart: always
#-----------------------DUCKDNS----------------------------------
  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=America/Colombia
      - TOKEN=daa034b7-046f-4008-b840-0b9833182928
      - LOG_FILE=flase
    restart: unless-stopped
#------------------------PORTAINER------------------------------
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart:  always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    ports:
      - 9000:9000
#----------------------------MOSQUITTO--------------------------------
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001" 
    volumes:
      - /home/pi/Docker/mosquitto/config:/mqtt/config
      - /home/pi/Docker/mosquitto/data:/mqtt/data
      - /home/pi/Docker/mosquitto/log:/mqtt/log
#----------------------------NODE-RED---------------------------
  nodered:
    container_name: Node-red
    image: nodered/node-red:latest
    user: "1000:1000"
    restart: always
    ports:
      - 1880:1880
    volumes:
      - "/mnt/external/nr-personal:/data"
    networks:
      - public
volumes:
  nr-personal:
networks:
  public:
